Сервис получения погоды
MihailR1/FastAPI pull request #2
Opened 2023-12-12 09:44 UTC by MihailR1

Сервис получения погоды с яндекс апи
Как запустить через консоль или докер и получить ключи расписал в readme

2023-12-13 21:35 UTC, khoshov requested changes
Не смогу тут коменты написать рядом с кодом. Я бы логику вынес в отдельную директорию, обычно называют services. Для схемы можно тоже schemas сделать директорию. utils обычно это вспомогательные функции какие-то. То есть кажется тут лучше конкретизировать.

вместо 200 лучше использовать status.HTTP_200_OK

Вместо ConvertSchemaMixin кажется лучше использовать встроенные возможности pydantic (написал в телегу подробности)

2023-12-16 10:26 UTC, MihailR1 commented on app/schemas/validate_schemas.py
> +async def validate_response_to_schema(schema: Any, response: Mapping[str, str]):
Тут не знаю как тип аннотации задать, принимает pydantic схему, любую

2023-12-16 10:27 UTC, MihailR1 commented on app/schemas/response_schemas.py
> +    ] = Field(validation_alias=AliasPath('Point', 'pos'))
тут как-то сложно получается по коду, т.к нужно строку разделить на 2е по пробелу - тогда получим long, latit

2023-12-16 10:28 UTC, MihailR1 commented on app/schemas/response_schemas.py
> +    ] = Field(validation_alias=AliasPath('Point', 'pos'))
и тип данных только как строка ставится, не ставится float

2023-12-18 20:35 UTC, khoshov approved these changes

2023-12-19 05:10 UTC, merged